version: 3

dotenv: [".env"]

includes:
  base:
    taskfile: ./scripts/tasks/base
  build:
    taskfile: ./scripts/tasks/build
  run:
    taskfile: ./scripts/tasks/run
  fe:
    taskfile: ./scripts/tasks/fe
  e2e:
    taskfile: ./scripts/tasks/e2e
  test:
    taskfile: ./scripts/tasks/test
  format:
    taskfile: ./scripts/tasks/format

tasks:
  run:
    desc: "运行本地服务"
    cmds:
      - task: run:web
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  test:
    desc: "运行所有测试"
    cmds:
      - task: test:all

  e2e:
    desc: "运行 E2E 测试"
    cmds:
      - task: e2e:all
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
