version: 3

tasks:
  install:
    desc: "安装 E2E 依赖和浏览器"
    cmds:
      - go run ./scripts/go-scripts e2e-install

  all:
    desc: "运行全部 E2E 测试"
    deps: [":build:web"]
    cmds:
      - go run ./scripts/go-scripts e2e {{.CLI_ARGS}}

  run:
    desc: "运行全部 E2E 测试"
    deps: [":e2e:all"]

  case:
    desc: "运行指定 E2E 用例"
    deps: [":build:web"]
    cmds:
      - go run ./scripts/go-scripts e2e --case {{.CLI_ARGS}}
